const express=require('express')
const { createUser, loginuser, getallusers, getauser, deleteUser, updateUser, blockUser, unblockUser, handleRefreshToken, logout, updatePassword, forgotPasswordToken, resetPassword, Adminloginuser, getWishList, saveAddress, userCart, getCart, deleteCart, applyCoupon, createOrder, getOrders, updateOrderStatus } = require('../controller/userCtrl')
const {authMiddleWare} = require('../middlewares/authMiddleWare')
const router=express.Router()


// router.route('/')
//     .post(createUser)
router.post('/create',createUser)
router.post('/forgot',forgotPasswordToken)
router.put('/reset-password/:token',resetPassword)
router.post('/adminlogin',Adminloginuser)
router.post('/login',loginuser)
router.get('/logout',logout)
router.get('/allusers',getallusers)
router.get('/refresh',handleRefreshToken)
router.get('/allusers/:id',getauser)
router.delete('/delete/:id',deleteUser)
router.put('/update/:id',authMiddleWare,updateUser)
router.get('/:id',authMiddleWare,getauser)
router.put('/block/:id',blockUser)
router.put('/unblock/:id',unblockUser)
router.put('/password/:id',updatePassword)
router.get('/wishlist/:id',getWishList)
router.put('/saveaddress/:id',saveAddress)
router.post('/cart/:id',userCart)
router.get('/getcart/:id',getCart)
router.delete('/deletecart/:id',deleteCart)
router.post('/applycoupon/:id',applyCoupon)
router.post('/order/:id',createOrder)
router.get('/allorders/:id',getOrders)
router.put('/updateorder/:id',updateOrderStatus)

module.exports=router